### 3.2.3 - Essence of tensors

In [1]:
import torch
og_tensor = torch.tensor([[4.0, 1.0],[2.0, 3.0],[5.0, 3.0]]) # passing python 2D list to the torch.tensor contructor

print(og_tensor, og_tensor.shape)

tensor([[4., 1.],
        [2., 3.],
        [5., 3.]]) torch.Size([3, 2])


In [6]:
new_tensor = og_tensor[0] # JUST A VIEW. no new tensor object is created and allocated new chunk of memory. VISIT 3.7
new_tensor

tensor([4., 1.])

### 3.3

In [ ]:
some_list = torch.tensor([i for i in range(10)])

print(some_list[1:4]) # [1] inclusive (included), [4] ignored - [1], [4] means some_list[1], some_list[4]
print(some_list[1:])
print(some_list[:4])
print(some_list[:-1]) # [-1] ignored, until the element before print(some_list[-1]
print(some_list[1:4:2]) # [1] and [4] both inclusive, = [1], [3]

tensor([1, 2, 3])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([1, 3])


In [18]:
# Adds a dim before dim 0 -  like some_list.unsqueeze()



print(some_list.size())
print(some_list[None].size())

torch.Size([10])
torch.Size([1, 10])


'ls' is not recognized as an internal or external command,
operable program or batch file.
